---
title: "General Assessment"
description: "Post description"
author: "Ahmed Homoudi"
---

**Remarks:**

-   Use any programming languages you would like to. Keep in mind that
    it should be a language capable of handling scientific computations.
    We, generally, are familiar with R and Python.

-   The Internet is filled with Q&A regarding programming, and there is
    definitely someone who tried to program what you want to do. So,
    Google is your friend.

-   Please submit your code and results in a readable manner.

-   Comment your code, and leave notes, therefore, you or other people
    can read it easily later.
    
# Task 1: String manipulation

Write a code that can do these tasks:

-   Print \"Hello World!\".

-   Check out your working directory (WD) and Print it.

-   Make a new directory from within your code.

-   Change your WD to the newly created directory.

-   Create a TXT file in the WD, and Write in it:\
    \"Hello world!\"\
    \"I'm your name\"

-   Read that text file and replace \"World\" with \"Dresden\" or any
    other word, and finally write it to the TXT file.

-   Advanced task: If you want to challenge yourself, this is the
    chance:

    -   Create a vector of string that has a length of 50 elements. Each
        element is, for example, \"Hello! I'm file number n\". n is the
        order of the string in the vector.

    -   Loop over the vector elements, and write each element to a TXT
        file called \"file_n.txt\"

    -   List all these TXT files and read their content to one variable,
        and write this variable to a TXT file called \"all_n.txt\"

    -   Delete the other 50 files.

# Task 2: One Dimensional Data

Go to [Climate Change Knowledge
Portal](https://climateknowledgeportal.worldbank.org/download-data).
Download a time series data of precipitation and mean temperature for
your country or area of interest. After downloading the data as shown in
Figure [1](#fig001){reference-type="ref" reference="fig001"}, continue
in the same code you started in Task 1 and write a script that:

![Climate Change Knowledge Portal. CRU
(Observed)](Screenshot from 2022-08-05 10-27-08.png){#fig001
width="\\textwidth"}

-   Read the two CSV file you downloaded correctly.

-   Plot a time series of the two variables.

-   Produce a long-term climatology from the data. Look at the first
    left plot
    [here](https://en.climate-data.org/europe/bulgaria/german/german-198333/).

-   Advanced task: If you want to challenge yourself, this is another
    chance:

    -   calculate the yearly accumulated rainfall and plot it as
        bar-plot where x-axis is years.

    -   add a trend line with slope value on the chart.

# Task 3: Two Dimensional Data

Go to [CloudStore, TU
Dresden](https://cloudstore.zih.tu-dresden.de/index.php/s/Bks4sAZbPD46SZ7)
and download the file *task3_file.nc*. The file contains 2D data
(excluding time dimension) from ERA5 reanalysis including 2 m
temperature, total precipitation, u and v wind compounds. After
downloading the file, continue in the same code you started in tasks
above and write a script that:

-   Read the netCDF file.

-   Extract different variables from the file.

-   Determine the spatial resolution of data in longitude and latitude
    directions.

-   search for the grid cell that represents your region of interest,
    and extract the variables as monthly time series.

-   Plot 2 m temperature, total precipitation in one time series plot
    (Hint: two different y-axis).

-   Plot the u and v wind components as well as wind speed.

-   Advance task: If you want to challenge yourself, this is another
    chance:

    -   Aggregate the variables on the time axis and produce a long term
        climatology.

    -   Plot a map focused on your region showing long-term climatology
        of 2 m temperature, total precipitation, and wind. (Hint: the
        data has dimension of (time=264, lat=180, lon=360), a worldwide
        climatology should have (time=1, lat=180, lon=360)).

    -   Try to add map legends, shape files indicating the borders and
        every features that is part of map standards.

    -   You could plot wind speed and directions as arrows.

# Task 4: Three Dimensional Data (Advanced)

Go to [CloudStore, TU
Dresden](https://cloudstore.zih.tu-dresden.de/index.php/s/Bks4sAZbPD46SZ7)
and download the file *task4_file.nc*. The file contains 3D data
(excluding time dimension) from ERA5 reanalysis including temperature,
relative humidity, geopotential (See more about it
[here](https://apps.ecmwf.int/codes/grib/param-db/?id=129)), and u and v
wind compounds. After downloading the file, continue in the same code
you started in tasks above and write a script that:

-   Read the netCDF file.

-   Extract different variables from the file.

-   Determine the spatial resolution of data in longitude and latitude
    directions.

-   Search for the grid cell that represents your region of interest,
    and extract the variables as monthly time series. (Hint: the file
    contains atmospheric data on variable levels for one year. So the
    monthly time series should a table for the location you picked
    containing 3 columns: month, level, value)

-   Plot atmospheric profiles for different variable, where x-axis is
    the climatic variable, y-axis is pressure level or/and altitude.
    Start with plotting one month. Check [the first figure on the right
    there](https://en.wikipedia.org/wiki/U.S._Standard_Atmosphere).

-   Plot similar profile the u and v wind components as well as wind
    speed.

-   Advanced task: If you want to challenge yourself, this is another
    chance:

    -   In the plots above, add a profile line for each month for each
        variable.

::: center
**End**
:::
