---
title: "Research Topics"
author: "Ahmed Homoudi"
---

I wish to express complete transparency in our collaboration expectations. The acquisition of programming skills is imperative for us to work together effectively. Our endeavors encompass the management of extensive datasets and intricate simulations. Programming serves as a fundamental tool for achieving automation and optimizing efficiency within these contexts. To facilitate a successful partnership, I kindly request your commitment to acquiring programming proficiency. This will not only enhance our productivity but also contribute to the overall success of our collaboration. Your understanding and consideration in this matter are greatly appreciated.

# Analysis of CAPE and CIN from radiosondes for Germany

**Supervisors**: K. Barfus^1^ & A. Homoudi^2^ (Chair of Meteorology)

^1^ [klemens.barfus\@tu-dresden.de](mailto:klemens.barfus@tu-dresden.de) ^2^ [ahmed.homoudi\@tu-dresden.de](mailto:ahmed.homoudi@tu-dresden.de)

Vertical profiles of the atmosphere are measured using Radiosondes/ weather balloons. These measurements provide some insights if thunderstorms might happen by indices like CAPE and CIN. The project aims to fullfil the following objectives: - Relevant literature review. - Estimation of CAPE, CIN, & other atmospheric stability indices. - Systematic analysis and presentation of the results.

# Analysis of drop size distributions from the Tharandt distrometer with respect to rain erosion on wind turbines

Analysis of Vertical Profiles from WRF Simulations Application of the Hewson front detection algorithm to the Arabian Peninsula Assessing Future Changes of Climate Extreme Events in Sudan using CORDEX Ensemble Climatology of the Moisture Sources in the Arabian Peninsula using Lagrangian Method Establishment of Z-R relationships for the Arabian Peninsula Identification of Tropical cyclones in the Arabian Sea Sub-Basin Nearly raining clouds over the AP from CloudSat data Objective Identification and Characterisation of ITCZs in Arid and Semiarid Regions Rendering of mesoscale model outputs with focus on clouds and precipitation

# Analysis of Vertical Profiles from WRF Simulations

**Supervisors**: K. Barfus^1^ & A. Homoudi^2^ (Chair of Meteorology)

^1^ [klemens.barfus\@tu-dresden.de](mailto:klemens.barfus@tu-dresden.de)

^2^ [ahmed.homoudi\@tu-dresden.de](mailto:ahmed.homoudi@tu-dresden.de)

# Analysis of CAPE and CIN from radiosondes for Germany

**Supervisors**: K. Barfus^1^ & A. Homoudi^2^ (Chair of Meteorology)

^1^ [klemens.barfus\@tu-dresden.de](mailto:klemens.barfus@tu-dresden.de)

^2^ [ahmed.homoudi\@tu-dresden.de](mailto:ahmed.homoudi@tu-dresden.de)

# Analysis of drop size distributions from the Tharandt distrometer with respect to rain erosion on wind turbines

**Supervisors**: K. Barfus^1^ & A. Homoudi^2^ (Chair of Meteorology)

^1^ [klemens.barfus\@tu-dresden.de](mailto:klemens.barfus@tu-dresden.de)

^2^ [ahmed.homoudi\@tu-dresden.de](mailto:ahmed.homoudi@tu-dresden.de)

# Application of the Hewson front detection algorithm to the Arabian Peninsula

**Supervisors**: K. Barfus^1^ & A. Homoudi^2^ (Chair of Meteorology)

^1^ [klemens.barfus\@tu-dresden.de](mailto:klemens.barfus@tu-dresden.de)

^2^ [ahmed.homoudi\@tu-dresden.de](mailto:ahmed.homoudi@tu-dresden.de)

# Nearly raining clouds over the AP from CloudSat data

**Supervisors**: K. Barfus^1^ & A. Homoudi^2^ (Chair of Meteorology)

^1^ [klemens.barfus\@tu-dresden.de](mailto:klemens.barfus@tu-dresden.de)

^2^ [ahmed.homoudi\@tu-dresden.de](mailto:ahmed.homoudi@tu-dresden.de)

# Rendering of mesoscale model outputs with focus on clouds and precipitation

**Supervisors**: K. Barfus^1^ & A. Homoudi^2^ (Chair of Meteorology)

^1^ [klemens.barfus\@tu-dresden.de](mailto:klemens.barfus@tu-dresden.de)

^2^ [ahmed.homoudi\@tu-dresden.de](mailto:ahmed.homoudi@tu-dresden.de)

# Identification of Tropical cyclones in the Arabian Sea Sub-Basin

**Supervisors**: A. Homoudi^1^ & K. Barfus^2^ (Chair of Meteorology)

^1^ [ahmed.homoudi\@tu-dresden.de](mailto:ahmed.homoudi@tu-dresden.de)

^2^ [klemens.barfus\@tu-dresden.de](mailto:klemens.barfus@tu-dresden.de)

**Background**:

Tropical cyclones (Tcs) are one of the most devastating events and are expected to intensify under global warming. TCs are one of the most difficult events to predict and understand in the atmosphere. Storm surges associated with severe TCs are the most damaging rather than rain and strong winds. Under a warming climate, the frequency of the TCs in the Arabian Sea is increasing. Additionally, the TCs are projected to intensify, with a greater proportion of storms having more damaging wind speeds, higher storm surges, and more extreme rainfall rates. Besides the fact that TCs are spatially shifted in Climate models, the detection criteria vary tremendously between climate models and remote sensing data. Therefore, the characteristics of TCs should be understood through direct, objective and automatic detection and tracking methods in reanalyses and model simulations to contribute to developing integrated planning for Climate Change.

**Objectives**:

-   Detecting tropical cyclones genesis from Remote sensing data (e.g., IR images)
-   Identification of tropical cyclones in ERA5 reanalysis data.
-   Comparison of the findings with observation data (i.e. IBTrACS)
-   Systematic presentation of findings

**Skills** (not compulsory but preferred or strong motivation to learn):

-   Programming with R or Python
-   Familiarity with Linux and shell scripting
-   Acquaintance with climate data formats (e.g., NetCDF)

# Climatology of the Moisture Sources in the Arabian Peninsula using Lagrangian Method

**Supervisors**: A. Homoudi^1^ & K. Barfus^2^ (Chair of Meteorology)

^1^ [ahmed.homoudi\@tu-dresden.de](mailto:ahmed.homoudi@tu-dresden.de)

^2^ [klemens.barfus\@tu-dresden.de](mailto:klemens.barfus@tu-dresden.de)

**Background**:

The Arabian Peninsula is one of the aridest regions on earth, and it is a region of reciprocal influences of tropical and extra-tropical configurations. Several configurations govern the climate of the region (e.g., Mediterranean, monsoon, subtropical, tropical, and Saharan influences). It is important to understand the configuration contributing to precipitation events in such an arid region. One essential ingredient for precipitation events is the available moisture, which can, e.g. be transported in organised bands known as atmospheric rivers. These different means of moisture transport are responsible for some of the global hydro-climatic extremes. In the Arabian Peninsula, they are responsible for the record floods during March 2019. On the other hand, these extreme precipitation events might be the only source of groundwater recharge.

**Objectives**:

-   Literature review: Sources of moisture, precipitation systems, Lagrangian analysis.
-   Calculating forward/backward trajectories to infer water vapour transport to the Arabian Peninsula.
-   Identifying trajectories and moisture contributions leading to precipitation events on the Arabian Peninsula.
-   Obtaining water vapour sources and pathways by Lagranto model using ERA5 reanalysis.
-   Systematic presentation of findings with comprehensive interpretation of the results.

**Skills** (not compulsory but preferred or strong motivation to learn):

# Assessing Future Changes of Climate Extreme Events in Sudan using CORDEX Ensemble

**Supervisors**: A. Homoudi^1^ & K. Barfus^2^ (Chair of Meteorology)

^1^ [ahmed.homoudi\@tu-dresden.de](mailto:ahmed.homoudi@tu-dresden.de)

^2^ [klemens.barfus\@tu-dresden.de](mailto:klemens.barfus@tu-dresden.de)

**Background**:

**Objectives**:

**Skills** (not compulsory but preferred or strong motivation to learn):

# Objective Identification and Characterisation of ITCZs in Arid and Semiarid Regions

**Supervisors**: A. Homoudi^1^ & K. Barfus^2^ (Chair of Meteorology)

^1^ [ahmed.homoudi\@tu-dresden.de](mailto:ahmed.homoudi@tu-dresden.de)

^2^ [klemens.barfus\@tu-dresden.de](mailto:klemens.barfus@tu-dresden.de)

**Background**:

**Objectives**:

**Skills** (not compulsory but preferred or strong motivation to learn):

# Establishment of Z-R relationships for the Arabian Peninsula

**Supervisors**: A. Homoudi^1^ & K. Barfus^2^ (Chair of Meteorology)

^1^ [ahmed.homoudi\@tu-dresden.de](mailto:ahmed.homoudi@tu-dresden.de)

^2^ [klemens.barfus\@tu-dresden.de](mailto:klemens.barfus@tu-dresden.de)
